import authController from './auth'
import categoryController from './category'
import notFound from './notFound'
import courseController from './course'
import contentController from './content'
import videoController from './video'
import progressController from './progress'
import quizController from './quiz'
import assignmentController from './assignment'
export {assignmentController, authController, categoryController, courseController, contentController, videoController, progressController, quizController, notFound}